### ISSUE TITLE
Traceback Error

### ISSUE THREAD

**Issue by ankushsethi** [Pbatch/ClashRoyaleBuildABot#42]
When trying to execute the main.py from examples folder, I keep getting this error.

Traceback (most recent call last):
  File "C:\Users\ankus\Downloads\ClashRoyaleBuildABot-main\ClashRoyaleBuildABot-main\example\main.py", line 18, in <module>
    main()
  File "C:\Users\ankus\Downloads\ClashRoyaleBuildABot-main\ClashRoyaleBuildABot-main\example\main.py", line 14, in main
    bot.run()
  File "C:\Users\ankus\Downloads\ClashRoyaleBuildABot-main\ClashRoyaleBuildABot-main\example\custom_bot.py", line 47, in run
    self._preprocess()
  File "C:\Users\ankus\Downloads\ClashRoyaleBuildABot-main\ClashRoyaleBuildABot-main\example\custom_bot.py", line 28, in _preprocess
    for unit in v['positions']:
KeyError: 'positions'

I have the dependencies installed as per the guide. Any suggestions on what am i doing wrong?

![image](https://user-images.githubusercontent.com/22005886/178137995-50b1a99e-2c09-4db9-acb8-dc41e2b821b1.png)

**Comment by Pbatch** [comment]
Ah damn, this is my fault. In the last MR I changed the state so that the units are split into 'ally' and 'enemy' and updated the bots, but forgot to change example bot.

Let me apply a quick hotfix.

**Comment by Pbatch** [comment]
@all-contributors please add @ankushsethi for reporting a bug.

This is fixed on master now :)

**Comment by ankushsethi** [comment]
Hello @Pbatch , Looks like I am still facing the same issue..
So, i have updated the bot using pip install command and verified the bot version is now updated to latest

![image](https://user-images.githubusercontent.com/22005886/178483284-286bf71e-882e-4420-accc-9b760da07379.png)

Then tried to execute the example/main.py again and saw the error again..
I also tried to execute the random bot but nothing happens, it just exits it seems. Can you please help on this?

![image](https://user-images.githubusercontent.com/22005886/178483891-d5adc12d-0de2-42e8-87a1-0425bc787926.png)

**Comment by Pbatch** [comment]
I think you have an old version of the code still because line 28 is different in the current master branch (with my fix).

![image](https://user-images.githubusercontent.com/37177749/178595142-e1a1cb3d-67ea-4a6a-b9a6-e401d24d9bea.png)

It looks like you're running the code locally, rather than using the version from the package manager.
Normally the path would look something like `C:\Users\SP\AppData\Local\Programs\Python\Python39\lib\site-packages\clashroyalebuildabot`

 Try deleting the `ClashRoyaleBuildABot-main` folder and cloning a new copy of the repo!
